:PROPERTIES:
#+TITLE: Dreams
#+AUTHOR:
#+EMAIL:
#+DATE: 2023-03-24 15:45:12
#+OPTIONS: toc:nil todo:nil
#+FILETAGS:
#+STARTUP:
:END:

* A Torre :long:macabre:pt_br:
:PROPERTIES:
:CREATED:  [2023-03-08 Wed 09:39]
:END:

Sonhei que estava visitando um amigo próximo em seu apartamento em uma grande torre luxosa e moderna, não lembro quem era o amigo, mas por alguma razão os pais dele eram os /meus/ pais.

A torre era localizada em uma grande região plana e construída, sendo todas as construções aí redor parecendo semi-futuristas em relação ao presente.
 De estética britalista em grande parte m, cheia de polígonos e retas de concerto e metal.

/Corte/

Durante um dia muito muito ventoso uma das construções ao redor da torre de repente simplesmente cai de lado, é uma grande torre de rádio com um formato esquisito, e tem praticamente a altura do prédio onde estamos, parece que faz pouco barulho e dano relativamente pra algo tão grande caindo.
Logo em seguida, como se isso fosse um aviso, a torre que estamos começa a oscilar violentamente como se estivéssemos em um terremoto.

Todos entram em pânico tentando descer a torre e pegar objetos importantes antes de evacuar a torre. Inicialmente fico bem confuso pelo chão oscilante, mas rapidamente faço um esforço para conseguir pegar meu celular e sair correndo. Tento ir para o elevador (‽‽) mas ele de alguma forma "morde" ou prende meu braço como se estivesse brincando comigo e agindo de forma infantil/semi-maliciosa, como se fosse alguma coisa /viva/ controlando o elevador (tenho a sensação que isso já aconteceu antes no sonho mas não me lembro). O elevador começa a descer com meu braço preso na porta, mas consigo soltar antes de me machucar falo para as pessoas comigo que vou descer de escada, mesmo o prédio tendo /muitos/ (30/60/100??) andares estarmos quase ou na cobertura.

/Corte/

Estamos nos base do prédio, onde está cheio de pessoas tentando saírem do prédio ao mesmo tempo, está nevando fortemente mesmo antes estando com o tempo limpo.

Estamos a beira de uma estrada extremamente larga, passando grandes veículos futuristas usando esteiras, quase parecendo equipamento industrial.
O pai de meu amigo sinaliza para um deles e ele para, mas quando vamos entrar no veículo há um engano e somente ele entra, acidentalmente indo para longe.

/Corte para algum lugar embaixo do prédio /

Há 3 pessoas ao redor de uma máquina baixa e comprida.
Cada uma carrega uma mochila amarela que se move e parece bombear algum fluido vermelho e parece levemente nojento/biológico para algo utilizado por um prédio além de bombear como se estivesse "batendo".

Uma das mochilas funcionais é carregada por um home de aparência asiática e extremamente sombrio.

Outra é carregada por uma mulher mais velha (~50) de aparência amistosa. Pergunto o que aconteceu, pois sua mochila parece estar lentamente falhando, além do fluido estar ficando amarelo.
Ela me explica que aquele coração falhou e não tem o que fazer. Eu sei que isso é diretamente relacionado às inclinações da torre anteriormente, além do comportamento "infantil" dos equipamentos do prédio. Agradeço e saio do ambiente.

/Corte para uma cena que não estou presente, numa forma de bar no térreo do prédio/

Um par de homens está sentado conversando, um deles (não identificado) pergunta para outro (parece ser o gerente do prédio) se realmente precisamos de 3.

/Intercalado com eles conversando é mostrado outra coisa/
(É mostrado o que parece ser um guerreiro poderoso, lutando com uma forma de criaturas da "noite" em uma nevasca)

O gerente responde veementemente ("sim sim sim")  que realmente não precisa de 3, mas..

(Quando as criaturas olham para o guerreiro, imediatamente é como se ele estivesse contra o vento em uma nevasca)

O tecido podre remanescente queima...

(O guerreiro parece estar utilizando de uma forma de literalmente um laser solar para matar as criaturas)

O resto então não é simplesmente só remover.

Acordei.

** Observações
:PROPERTIES:
:CREATED:  [2023-03-08 Wed 09:43]
:END:

Este sonho me lembra de algum filme ou livro e várias das imagens e 'cenas' foram extremamente marcantes visualmente, pena que não consigo transmitir isso de forma adequada.

A sensação que tive sobre a torre, é ter sido construída com o corpo de uma forma de vida gigante, como se a sua "força vital" fosse /necessária/ para construir e sustentar um prédio tão grande. Por alguma razão sabia que a entidade de alguma forma era relacionada com um grande touro.

Tem fortes inspirações Bio/Flesh Punk.

A situation do meu pai se perdendo no táxi é bem compreensível.

O poder do guerreiro é literalmente o solar flare do mod Space exploration do Factorio.

Também me lembra muito da premissa de um livro (bem ruim) que comecei a ler uma vez, também chamado de "A torres" ou algo similar.
